// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/tailbeat.proto

package tail

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogCollector_PushLog_FullMethodName      = "/LogCollector/PushLog"
	LogCollector_PushLogBatch_FullMethodName = "/LogCollector/PushLogBatch"
)

// LogCollectorClient is the client API for LogCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogCollectorClient interface {
	PushLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogAck, error)
	PushLogBatch(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*LogAck, error)
}

type logCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogCollectorClient(cc grpc.ClientConnInterface) LogCollectorClient {
	return &logCollectorClient{cc}
}

func (c *logCollectorClient) PushLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogAck)
	err := c.cc.Invoke(ctx, LogCollector_PushLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logCollectorClient) PushLogBatch(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*LogAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogAck)
	err := c.cc.Invoke(ctx, LogCollector_PushLogBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogCollectorServer is the server API for LogCollector service.
// All implementations must embed UnimplementedLogCollectorServer
// for forward compatibility.
type LogCollectorServer interface {
	PushLog(context.Context, *LogEntry) (*LogAck, error)
	PushLogBatch(context.Context, *LogBatch) (*LogAck, error)
	mustEmbedUnimplementedLogCollectorServer()
}

// UnimplementedLogCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogCollectorServer struct{}

func (UnimplementedLogCollectorServer) PushLog(context.Context, *LogEntry) (*LogAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PushLog not implemented")
}
func (UnimplementedLogCollectorServer) PushLogBatch(context.Context, *LogBatch) (*LogAck, error) {
	return nil, status.Error(codes.Unimplemented, "method PushLogBatch not implemented")
}
func (UnimplementedLogCollectorServer) mustEmbedUnimplementedLogCollectorServer() {}
func (UnimplementedLogCollectorServer) testEmbeddedByValue()                      {}

// UnsafeLogCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogCollectorServer will
// result in compilation errors.
type UnsafeLogCollectorServer interface {
	mustEmbedUnimplementedLogCollectorServer()
}

func RegisterLogCollectorServer(s grpc.ServiceRegistrar, srv LogCollectorServer) {
	// If the following call panics, it indicates UnimplementedLogCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogCollector_ServiceDesc, srv)
}

func _LogCollector_PushLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogCollectorServer).PushLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogCollector_PushLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogCollectorServer).PushLog(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogCollector_PushLogBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogCollectorServer).PushLogBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogCollector_PushLogBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogCollectorServer).PushLogBatch(ctx, req.(*LogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// LogCollector_ServiceDesc is the grpc.ServiceDesc for LogCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LogCollector",
	HandlerType: (*LogCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushLog",
			Handler:    _LogCollector_PushLog_Handler,
		},
		{
			MethodName: "PushLogBatch",
			Handler:    _LogCollector_PushLogBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tailbeat.proto",
}
