// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/tailbeat.proto

package tail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_tailbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_tailbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_tailbeat_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_api_tailbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_tailbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_api_tailbeat_proto_rawDescGZIP(), []int{1}
}

func (x *LogBatch) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type LogAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messsage      string                 `protobuf:"bytes,2,opt,name=messsage,proto3" json:"messsage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_api_tailbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_tailbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_api_tailbeat_proto_rawDescGZIP(), []int{2}
}

func (x *LogAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogAck) GetMesssage() string {
	if x != nil {
		return x.Messsage
	}
	return ""
}

type SteamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedCount int32                  `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SteamAck) Reset() {
	*x = SteamAck{}
	mi := &file_api_tailbeat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteamAck) ProtoMessage() {}

func (x *SteamAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_tailbeat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteamAck.ProtoReflect.Descriptor instead.
func (*SteamAck) Descriptor() ([]byte, []int) {
	return file_api_tailbeat_proto_rawDescGZIP(), []int{3}
}

func (x *SteamAck) GetReceivedCount() int32 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *SteamAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_tailbeat_proto protoreflect.FileDescriptor

const file_api_tailbeat_proto_rawDesc = "" +
	"\n" +
	"\x12api/tailbeat.proto\"\xed\x01\n" +
	"\bLogEntry\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x123\n" +
	"\bmetadata\x18\x05 \x03(\v2\x17.LogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\bLogBatch\x12\x1d\n" +
	"\x04logs\x18\x01 \x03(\v2\t.LogEntryR\x04logs\">\n" +
	"\x06LogAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bmesssage\x18\x02 \x01(\tR\bmesssage\"K\n" +
	"\bSteamAck\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\x05R\rreceivedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2Q\n" +
	"\fLogCollector\x12\x1d\n" +
	"\aPushLog\x12\t.LogEntry\x1a\a.LogAck\x12\"\n" +
	"\fPushLogBatch\x12\t.LogBatch\x1a\a.LogAckB\x16Z\x14tailbeatpd/tail;tailb\x06proto3"

var (
	file_api_tailbeat_proto_rawDescOnce sync.Once
	file_api_tailbeat_proto_rawDescData []byte
)

func file_api_tailbeat_proto_rawDescGZIP() []byte {
	file_api_tailbeat_proto_rawDescOnce.Do(func() {
		file_api_tailbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tailbeat_proto_rawDesc), len(file_api_tailbeat_proto_rawDesc)))
	})
	return file_api_tailbeat_proto_rawDescData
}

var file_api_tailbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_tailbeat_proto_goTypes = []any{
	(*LogEntry)(nil), // 0: LogEntry
	(*LogBatch)(nil), // 1: LogBatch
	(*LogAck)(nil),   // 2: LogAck
	(*SteamAck)(nil), // 3: SteamAck
	nil,              // 4: LogEntry.MetadataEntry
}
var file_api_tailbeat_proto_depIdxs = []int32{
	4, // 0: LogEntry.metadata:type_name -> LogEntry.MetadataEntry
	0, // 1: LogBatch.logs:type_name -> LogEntry
	0, // 2: LogCollector.PushLog:input_type -> LogEntry
	1, // 3: LogCollector.PushLogBatch:input_type -> LogBatch
	2, // 4: LogCollector.PushLog:output_type -> LogAck
	2, // 5: LogCollector.PushLogBatch:output_type -> LogAck
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_tailbeat_proto_init() }
func file_api_tailbeat_proto_init() {
	if File_api_tailbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tailbeat_proto_rawDesc), len(file_api_tailbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tailbeat_proto_goTypes,
		DependencyIndexes: file_api_tailbeat_proto_depIdxs,
		MessageInfos:      file_api_tailbeat_proto_msgTypes,
	}.Build()
	File_api_tailbeat_proto = out.File
	file_api_tailbeat_proto_goTypes = nil
	file_api_tailbeat_proto_depIdxs = nil
}
